spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pharmacyms?serverTimezone=GMT&allowMultiQueries=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: user
      password:

#  redis:
#    host: localhost
#    port: 6379
#    jedis:
#      pool:
#        max-wait: 30000
#        max-active: 10
#        max-idle: 20
#        min-idle: 0
#    connect-timeout: 3000